// apps/web/src/components/layout/ThemeSwitcher.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useThemeStore } from '@/stores/theme'
import { Sunny, Moon, Brush, Check } from '@element-plus/icons-vue'

const themes = [
  { key: 'uber', label: 'Uber' },
  { key: 'coinbase', label: 'Coinbase' },
  { key: 'rabbit', label: 'Rabbit' },
] as const

const themeStore = useThemeStore()
const colorTheme = ref('uber')
const mounted = ref(false)

function applyColorTheme(key: string) {
  colorTheme.value = key
  localStorage.setItem('nexus-color-theme', key)
  document.documentElement.setAttribute('data-theme', key)
}

onMounted(() => {
  colorTheme.value = localStorage.getItem('nexus-color-theme') || 'uber'
  mounted.value = true
})
</script>

<template>
  <!-- Show placeholder while not mounted to prevent layout shift -->
  <div v-if="!mounted" class="flex items-center gap-1">
    <el-button disabled circle :icon="Brush" />
    <el-button disabled circle :icon="Sunny" />
  </div>

  <div v-else class="flex items-center gap-1">
    <!-- Color theme selector -->
    <el-dropdown trigger="click" @command="applyColorTheme">
      <el-button circle :icon="Brush" aria-label="配色主题" />
      <template #dropdown>
        <el-dropdown-menu>
          <el-dropdown-item
            v-for="t in themes"
            :key="t.key"
            :command="t.key"
            :class="{ 'is-active': colorTheme === t.key }"
          >
            {{ t.label }}
            <el-icon v-if="colorTheme === t.key" class="ml-2" :size="14"><Check /></el-icon>
          </el-dropdown-item>
        </el-dropdown-menu>
      </template>
    </el-dropdown>

    <!-- Dark / Light toggle -->
    <el-button circle @click="themeStore.toggle()">
      <el-icon :size="16">
        <Sunny v-if="themeStore.theme === 'light'" />
        <Moon v-else />
      </el-icon>
    </el-button>
  </div>
</template>

// apps/web/src/components/theme-switcher.tsx
'use client';

import { useTheme } from 'next-themes';
import { useEffect, useState } from 'react';
import { Dropdown, Button } from '@heroui/react';
import { Moon, Sun, Palette, Car } from 'lucide-react';

const themes = [
  // { key: 'default', label: '默认', icon: Sun },
  { key: 'coinbase', label: 'Coinbase', icon: Palette },
  { key: 'uber', label: 'Uber', icon: Car },
  { key: 'rabbit', label: 'Rabbit', icon: Palette },
] as const;

export function ThemeSwitcher() {
  const [mounted, setMounted] = useState(false);
  const { theme: mode, setTheme: setMode } = useTheme();
  const [colorTheme, setColorTheme] = useState('coinbase');

  useEffect(() => {
    const stored = localStorage.getItem('nexus-color-theme') || 'coinbase';
    queueMicrotask(() => {
      setMounted(true);
      setColorTheme(stored);
    });
  }, []);

  const applyColorTheme = (key: string) => {
    setColorTheme(key);
    localStorage.setItem('nexus-color-theme', key);
    document.documentElement.setAttribute('data-theme', key);
  };

  if (!mounted) {
    return (
      <Button variant="ghost" isIconOnly isDisabled>
        <Sun className="h-[1.15rem] w-[1.15rem]" />
      </Button>
    );
  }

  return (
    <div className="flex items-center gap-1">
      {/* color theme selector */}
      <Dropdown>
        <Button isIconOnly aria-label="Menu" variant="secondary">
          <Palette className="h-[1.15rem] w-[1.15rem]" />
        </Button>
        <Dropdown.Popover>
          <Dropdown.Menu
            aria-label="选择配色主题"
            selectedKeys={new Set([colorTheme])}
            selectionMode="single"
            onAction={(key) => applyColorTheme(key as string)}
          >
            {themes.map((t) => (
              <Dropdown.Item key={t.key} id={t.key}>
                <t.icon className="h-4 w-4" />
                <span className="ml-2">{t.label}</span>
              </Dropdown.Item>
            ))}
          </Dropdown.Menu>
        </Dropdown.Popover>
      </Dropdown>

      {/* dark/light toggle */}
      <Button
        variant="ghost"
        isIconOnly
        onPress={() => setMode(mode === 'dark' ? 'light' : 'dark')}
      >
        {mode === 'dark' ? (
          <Moon className="h-[1.15rem] w-[1.15rem]" />
        ) : (
          <Sun className="h-[1.15rem] w-[1.15rem]" />
        )}
      </Button>
    </div>
  );
}
