// apps/web/src/components/auth/auth-card.tsx
import { Card, CardHeader, CardContent, CardFooter } from '@heroui/react';

interface AuthCardProps {
  title: string;
  description: string;
  children: React.ReactNode;
  footer?: React.ReactNode;
}

export function AuthCard({
  title,
  description,
  children,
  footer,
}: AuthCardProps) {
  return (
    <div className="flex min-h-screen items-center justify-center bg-surface-secondary px-4">
      <Card className="w-full max-w-sm">
        <CardHeader className="flex flex-col items-center gap-1 pb-0">
          <h1 className="text-xl font-semibold text-foreground">{title}</h1>
          <p className="text-sm text-foreground/60">{description}</p>
        </CardHeader>
        <CardContent>{children}</CardContent>
        {footer && (
          <CardFooter className="justify-center">{footer}</CardFooter>
        )}
      </Card>
    </div>
  );
}

// apps/web/src/modules/system/auth/components/AuthCard.vue
<script setup lang="ts">
defineProps<{
  title: string
  subtitle?: string
}>()
</script>

<template>
  <div
    class="min-h-screen flex items-center justify-center p-4"
    style="background-color: var(--surface-secondary)"
  >
    <div
      class="w-full max-w-md p-8 rounded-xl shadow-sm"
      style="background-color: var(--surface); border: 1px solid var(--border)"
    >
      <div class="text-center mb-6">
        <h1
          class="text-2xl font-bold"
          style="color: var(--foreground)"
        >
          {{ title }}
        </h1>
        <p
          v-if="subtitle"
          class="text-sm mt-2"
          style="color: var(--foreground); opacity: 0.6"
        >
          {{ subtitle }}
        </p>
      </div>
      <slot />
    </div>
  </div>
</template>
