// apps/web/src/views/Register.vue
<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { authApi, type CaptchaData } from '@/api/auth'
import { registerSchema, type RegisterFormValues } from '@/validations/auth'
import AuthCard from '@/components/auth/AuthCard.vue'

const router = useRouter()

const form = reactive<RegisterFormValues>({
  username: '',
  email: '',
  password: '',
  confirmPassword: '',
  captchaCode: '',
})

const errors = reactive<Partial<Record<keyof RegisterFormValues, string>>>({})
const captcha = ref<CaptchaData | null>(null)
const captchaLoading = ref(false)
const submitting = ref(false)
const serverError = ref('')

async function fetchCaptcha() {
  captchaLoading.value = true
  try {
    captcha.value = await authApi.getCaptcha()
  } catch {
    serverError.value = '获取验证码失败'
  } finally {
    captchaLoading.value = false
  }
}

async function handleSubmit() {
  errors.username = ''
  errors.email = ''
  errors.password = ''
  errors.confirmPassword = ''
  errors.captchaCode = ''
  serverError.value = ''

  const result = registerSchema.safeParse(form)
  if (!result.success) {
    for (const issue of result.error.issues) {
      const field = issue.path[0] as keyof RegisterFormValues
      if (!errors[field]) {
        errors[field] = issue.message
      }
    }
    return
  }

  submitting.value = true
  try {
    await authApi.register(
      form.username,
      form.email,
      form.password,
      captcha.value!.captchaId,
      form.captchaCode,
    )
    router.push('/login?registered=true')
  } catch (e) {
    serverError.value = e instanceof Error ? e.message : '注册失败'
    fetchCaptcha()
  } finally {
    submitting.value = false
  }
}

onMounted(() => {
  fetchCaptcha()
})
</script>

<template>
  <AuthCard title="注册" subtitle="创建你的 Nexus AI 账号">
    <form class="flex flex-col gap-4" @submit.prevent="handleSubmit">
      <div>
        <el-input v-model="form.username" placeholder="用户名" />
        <p v-if="errors.username" class="text-xs mt-1" style="color: var(--el-color-danger)">{{ errors.username }}</p>
      </div>

      <div>
        <el-input v-model="form.email" placeholder="邮箱" />
        <p v-if="errors.email" class="text-xs mt-1" style="color: var(--el-color-danger)">{{ errors.email }}</p>
      </div>

      <div>
        <el-input v-model="form.password" type="password" placeholder="密码" show-password />
        <p v-if="errors.password" class="text-xs mt-1" style="color: var(--el-color-danger)">{{ errors.password }}</p>
      </div>

      <div>
        <el-input v-model="form.confirmPassword" type="password" placeholder="确认密码" show-password />
        <p v-if="errors.confirmPassword" class="text-xs mt-1" style="color: var(--el-color-danger)">{{ errors.confirmPassword }}</p>
      </div>

      <div>
        <div class="flex gap-2">
          <el-input v-model="form.captchaCode" placeholder="验证码" />
          <div
            class="h-9 w-24 shrink-0 flex items-center justify-center rounded cursor-pointer"
            style="background-color: var(--surface-secondary)"
            @click="fetchCaptcha"
          >
            <span v-if="captchaLoading" class="text-xs">加载中...</span>
            <div v-else-if="captcha" v-html="captcha.svg" class="w-full h-full flex items-center justify-center" />
          </div>
        </div>
        <p v-if="errors.captchaCode" class="text-xs mt-1" style="color: var(--el-color-danger)">{{ errors.captchaCode }}</p>
      </div>

      <p v-if="serverError" class="text-sm text-center" style="color: var(--el-color-danger)">{{ serverError }}</p>

      <el-button type="primary" native-type="submit" :loading="submitting" class="w-full">
        注册
      </el-button>

      <p class="text-sm text-center" style="color: var(--foreground); opacity: 0.6">
        已有账号？<router-link to="/login" class="font-medium" style="color: var(--accent)">去登录</router-link>
      </p>
    </form>
  </AuthCard>
</template>

// apps/web/src/app/register/page.tsx
'use client';

import { useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { registerSchema, type RegisterFormValues } from '@/lib/validations/auth';
import { authApi, type CaptchaData, clearPublicKeyCache } from '@/lib/api/auth';
import { Input } from '@heroui/react';
import { Button } from '@heroui/react';
import { AuthCard } from '@/components/auth/auth-card';

export default function RegisterPage() {
  const router = useRouter();
  const [captcha, setCaptcha] = useState<CaptchaData | null>(null);

  const {
    register,
    handleSubmit,
    setError,
    setValue,
    formState: { errors, isSubmitting },
  } = useForm<RegisterFormValues>({
    resolver: zodResolver(registerSchema),
    defaultValues: { username: '', email: '', password: '', confirmPassword: '', captchaCode: '' },
  });

  const fetchCaptcha = useCallback(async () => {
    try {
      const data = await authApi.getCaptcha();
      setCaptcha(data);
      setValue('captchaCode', '');
    } catch {
      // 获取验证码失败，静默处理
    }
  }, [setValue]);

  useEffect(() => {
    fetchCaptcha();
  }, [fetchCaptcha]);

  const onSubmit = async (values: RegisterFormValues) => {
    if (!captcha?.captchaId) {
      setError('captchaCode', { message: '请先获取验证码' });
      return;
    }

    try {
      await authApi.register(
        values.username,
        values.email,
        values.password,
        captcha.captchaId,
        values.captchaCode,
      );
      router.push('/login');
    } catch (err) {
      const message = err instanceof Error ? err.message : '注册失败';
      // 解密失败说明公钥可能已过期，清除缓存让下次重新获取
      if (message.includes('解密') || message.includes('刷新')) {
        clearPublicKeyCache();
      }
      // 验证码错误时刷新
      fetchCaptcha();
      setError('root', { message });
    }
  };

  return (
    <AuthCard
      title="注册"
      description="创建您的账号"
      footer={
        <p className="text-sm text-foreground/60">
          已有账号？{' '}
          <Link
            href="/login"
            className="font-medium text-accent underline underline-offset-4"
          >
            登录
          </Link>
        </p>
      }
    >
      <form onSubmit={handleSubmit(onSubmit)} className="flex flex-col gap-4">
        {errors.root && (
          <div className="rounded-lg bg-danger/10 border border-danger/30 px-4 py-3 text-sm text-danger">
            {errors.root.message}
          </div>
        )}

        <div className="flex flex-col gap-1.5">
          <label className="text-sm font-medium text-foreground">用户名</label>
          <Input
            type="text"
            placeholder="2-64个字符，字母、数字、下划线、连字符和点"
            {...register('username')}
          />
          {errors.username && (
            <p className="text-xs text-danger">{errors.username.message}</p>
          )}
        </div>

        <div className="flex flex-col gap-1.5">
          <label className="text-sm font-medium text-foreground">邮箱</label>
          <Input
            type="email"
            placeholder="you@example.com"
            {...register('email')}
          />
          {errors.email && (
            <p className="text-xs text-danger">{errors.email.message}</p>
          )}
        </div>

        <div className="flex flex-col gap-1.5">
          <label className="text-sm font-medium text-foreground">密码</label>
          <Input
            type="password"
            placeholder="6-15位，需包含字母、数字、特殊符号中至少两种"
            {...register('password')}
          />
          {errors.password && (
            <p className="text-xs text-danger">{errors.password.message}</p>
          )}
        </div>

        <div className="flex flex-col gap-1.5">
          <label className="text-sm font-medium text-foreground">确认密码</label>
          <Input
            type="password"
            placeholder="请再次输入密码"
            {...register('confirmPassword')}
          />
          {errors.confirmPassword && (
            <p className="text-xs text-danger">{errors.confirmPassword.message}</p>
          )}
        </div>

        <div className="flex flex-col gap-1.5">
          <label className="text-sm font-medium text-foreground">验证码</label>
          <div className="flex items-center gap-3">
            <Input
              type="text"
              placeholder="请输入验证码"
              className="flex-1"
              maxLength={4}
              {...register('captchaCode')}
            />
            {captcha?.svg ? (
              <span
                className="cursor-pointer select-none shrink-0 rounded border border-divider"
                dangerouslySetInnerHTML={{ __html: captcha.svg }}
                onClick={fetchCaptcha}
                title="点击刷新验证码"
              />
            ) : (
              <div className="w-[150px] h-[50px] rounded border border-divider bg-surface-secondary animate-pulse shrink-0" />
            )}
          </div>
          {errors.captchaCode && (
            <p className="text-xs text-danger">{errors.captchaCode.message}</p>
          )}
        </div>

        <Button
          type="submit"
          variant="primary"
          className="w-full"
          isPending={isSubmitting}
        >
          注册
        </Button>
      </form>
    </AuthCard>
  );
}
