// apps/web/src/app/ai-applications/page.tsx
'use client';

import { MainLayout } from '@/components/layout/main-layout';
import { Card, CardContent, CardHeader } from '@heroui/react';
import { Button } from '@heroui/react';

export default function AiApplicationsPage() {
  return (
    <MainLayout>
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-semibold text-foreground">
          AI 应用中心
        </h1>
        <Button variant="primary">+ 创建 AI 应用</Button>
      </div>
      <div className="grid grid-cols-3 gap-4">
        {[
          {
            name: '💰 财务助手',
            desc: 'KB: 财务 · WF: Reflection · 🤖 DeepSeek',
          },
          {
            name: '👥 HR 助手',
            desc: 'KB: HR · WF: RAG · 🤖 Qwen',
          },
          {
            name: '🔧 研发助手',
            desc: 'KB: R&D · WF: ReWOO · 🤖 GPT-4o',
          },
        ].map((app) => (
          <Card key={app.name}>
            <CardHeader>
              <h2 className="text-base font-semibold text-foreground">
                {app.name}
              </h2>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-foreground/60">{app.desc}</p>
            </CardContent>
          </Card>
        ))}
      </div>
    </MainLayout>
  );
}

// apps/web/src/views/AiApplications.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { Plus } from '@element-plus/icons-vue'
import { useAiApplications, useDeleteAiApplication } from '@/composables/use-ai-applications'
import AppCard from '@/components/ai-applications/AppCard.vue'

const router = useRouter()
const { data: apps, isLoading } = useAiApplications()
const deleteMutation = useDeleteAiApplication()

function handleView(id: string) { router.push(`/ai-applications/${id}`) }
function handleDelete(id: string) { deleteMutation.mutate(id) }
</script>

<template>
  <div>
    <div class="flex items-center justify-between mb-6">
      <h1 class="text-2xl font-semibold" style="color: var(--foreground)">AI 应用</h1>
      <el-button type="primary" :icon="Plus" @click="router.push('/ai-applications/new')">创建应用</el-button>
    </div>

    <div v-if="isLoading" class="flex justify-center py-12">
      <el-icon class="is-loading" :size="24"><Plus /></el-icon>
    </div>

    <div v-else-if="apps && Array.isArray(apps) && apps.length > 0" class="grid grid-cols-3 gap-4">
      <AppCard
        v-for="app in apps"
        :key="(app as Record<string,string>).id"
        :id="(app as Record<string,string>).id"
        :name="(app as Record<string,string>).name"
        @view="handleView"
        @delete="handleDelete"
      />
    </div>

    <el-empty v-else description="暂无 AI 应用" />
  </div>
</template>
