// apps/web/src/components/layout/main-layout.tsx
import { Sidebar } from './sidebar';
import { Header } from './header';

export function MainLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex h-screen overflow-hidden">
      <Sidebar />
      <div className="flex flex-1 flex-col overflow-hidden">
        <Header />
        <main className="flex-1 overflow-y-auto bg-surface-secondary p-6">{children}</main>
      </div>
    </div>
  );
}

// apps/web/src/layouts/MainLayout.vue
<script setup lang="ts">
import AppSidebar from '@/components/layout/AppSidebar.vue'
import AppHeader from '@/components/layout/AppHeader.vue'
</script>

<template>
  <div class="flex h-screen overflow-hidden">
    <AppSidebar />
    <div class="flex flex-1 flex-col overflow-hidden">
      <AppHeader />
      <main
        class="flex-1 overflow-y-auto px-5 py-4"
        style="background-color: var(--surface-secondary)"
      >
        <router-view />
      </main>
    </div>
  </div>
</template>
